name: BlueMapSpawn
version: '${project.version}'
main: be.renaud11232.bluemapspawn.BlueMapSpawn
api-version: '1.13'
depend:
  - BlueMap
authors:
  - Renaud11232
description: '${project.description}'
website: '${project.url}'
